# Generated by Django 3.2.9 on 2021-11-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=12, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('point', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('birth', models.DateField()),
            ],
        ),
    ]
